configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/brainbase-egrigokhan%2Fbrainbase-08ae1ff5d23bf55fb80b97659560a13a3d627ccba5ac5f8478157e9a51a32793.yml
